highlighter: rouge
baseurl: /alibuild
menu_header: BITS
menu:
  -
    name: quick.html
    label: QUICKSTART
  -
    name: user.html
    label: USER MANUAL
  -
    name: reference.html
    label: REFERENCE
  -
    name: troubleshooting.html
    label: TROUBLESHOOTING
  -
    name: https://alice-doc.github.io/alice-analysis-tutorial/building/
    label: ALICE TUTORIAL
defaults:
  -
    scope:
      path: "basic/"
      type: "posts"
    values:
      category: "basic"
      layout: "main"
